# Generated by Django 4.2.16 on 2024-12-10 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_blogpost_likes_count'),
        ('comments', '0002_alter_usercomments_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomments',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blogs.blogpost'),
        ),
    ]
